### ISSUE TITLE
ticket test zendesk -> github -> taiga

### ISSUE THREAD

**Issue by sinaoned** [naoned/test-icescrum-taiga#2]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#6141](https://naoned.zendesk.com/agent/tickets/6141)
**Priority:** high
**Group:** Equipe support
**Requester:** support-technique@naoned.fr
**Assignee:** Experts Techniques
**Issue escalated by:** Experts Techniques
**Produit et module:** portail_de_valorisation
**Version du produit:** version
**Navigateur internet:** chrome

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis interdum mauris, a laoreet dui. Nam imperdiet dolor mi, ut rutrum elit auctor et. Fusce interdum tortor lacus, nec varius massa aliquam a. Nullam convallis pulvinar risus sit amet ullamcorper. Aenean varius turpis ut posuere mattis. Aenean facilisis imperdiet accumsan. Sed sem felis, aliquam et consequat sed, viverra vel ligula. Proin varius vel nibh id interdum. Vivamus id orci id diam pharetra aliquet. Fusce finibus, nisi vel dapibus semper, ex eros tempor ipsum, at aliquam purus augue vel leo. Sed lacus ex, commodo vel tincidunt non, suscipit sit amet quam. Cras nec tristique sapien. Suspendisse eu massa ac ipsum ultrices maximus sit amet a diam. Nullam nec blandit velit, consectetur commodo ex. Suspendisse laoreet ligula et maximus ullamcorper.<br>
</div></blockquote>

**Comment by myancat** [comment]
commentaire dans github

**Comment by myancat** [comment]
test
